### PR TITLE
ENH: Pin `matplotlib` package version

### PR DESCRIPTION
**Pull request by jhlegarreta**
Pin `matplotlib` package version.

Fixes:
```
ImportError: cannot import name 'get_renderer' from 'matplotlib.tight_layout'
(/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/matplotlib/tight_layout.py)
```

raised at:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3298335648/jobs/5440315644#step:13:132

### CODE REVIEW

**Comment by jhlegarreta** [comment]
- The `Website` build failure is unrelated and should have been solved in PR #213 (this branch started from the immediately previous commit).
- The `Build, test` failure:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3299697899/jobs/5443364654#step:13:132
stems from the fact that the checked out commit does not correspond to this commit, but to the immediately previous commit:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3299697899/jobs/5443364654#step:8:386

Looks like a bit is missing in the GHA config file to check out the proper commit, or an issue in the GHA end. `v3` is also out (but similar problems have been reported).

In any case, merging as the previous builds with `matplotlib 3.5.3` were working.

**Comment by jhlegarreta** [comment]
The website is being built successfully:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3303231017

The tests are passing:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/3303231018
